### ISSUE TITLE
Showing PullUpController as opend

### ISSUE THREAD

**Issue by QaiserAbbas** [MarioIannotta/PullUpController#21] opened 2018-09-05 11:02 UTC
I just want to show the pullupcontroller as opened, when i launch first.
Then it must be normal, By pulling down, it will get down and vice versa?

Is there any property like that ?

**Comment by MarioIannotta** [comment] 2018-09-12 19:28
Hi @QaiserAbbas I've just pushed some changes in [`bugfix/fix-initial-state`](https://github.com/MarioIannotta/PullUpController/tree/bugfix/fix-initial-state). 
You can achieve the effect you're talking about in the demo project by select "Expanded" as initial state and by tapping "Remove" then "Add".

You can know more on how the bug has been fixed here: https://github.com/MarioIannotta/PullUpController/commit/e52ad681ee553ca9216398ea009eb542080556e8

Let me know what do you think of the fix.

**Comment by MarioIannotta** [comment] 2018-09-12 19:29
Since this issue is a duplicate of https://github.com/MarioIannotta/PullUpController/issues/21 let's discuss there futhers details.

**Closed as completed by MarioIannotta** 2018-09-12 19:29 UTC
Labels: duplicate
